#!/usr/bin/python3
import os
import sys
import json
import shutil
import argparse

# Parse args and dispatch
parser = argparse.ArgumentParser()
parser.add_argument("path", help="Ignition file")
args = parser.parse_args()

if args.path == '-':
    f = sys.stdin
else:
    f = open(args.path)
ign = json.load(f)
v = ign['ignition']['version']
if v != '3.0.0':
    raise SystemExit(f"Unsupported version {v}")
ign['ignition']['version'] = '2.2.0'
for f in ign['storage'].get('files', []):
    f['filesystem'] = "root"
    append = f.get('append')
    if append is not None:
        f['append'] = True
        if len(append) != 1:
            raise SystemExit(f"Can't handle multiple append: {f['path']}")
        f['contents'] = append[0]
json.dump(ign, sys.stdout)


